# step-1 -- getting a base image -- apline for not heavy deauty work
FROM alpine

# step-2 -- install a software
RUN apk add binutils

# step-2.5 -- configure a software -- not mandotary


# step-3 -- set default commands
CMD [ "npm" "install" ]
